### ISSUE TITLE
p7zip-desktop is adamant that vim.tiny is the only editor worth using

### ISSUE THREAD

**Issue by RogueScholar** [ErnyTech/p7zip#7]
...and wouldn't you know it, I'm a devout member of the Church of Emacs; I've even got a candle with a picture of Saint IGNUtius on the front to light when my keyboard mappings go cattywampus without explanation. :pray: :prayer_beads: :scroll: :rofl:

Seriously though, I'd be cool with mcedit, or micro...if it's Happy Hour I'd even order off the GUI menu and edit some archive files in Kate. Any idea where that preference gets hardcoded in and the best way to override it? I don't want to go digging around in the muck and find a sneaky workaround only to find it gets undone every time the snap refreshes; I've been down that lonesome road too many times already.

Any insight you can share would be most appreciated, and thanks for bringing a good old tool back into service. :vulcan_salute:

**Comment by ErnyTech** [comment]
Fixed by https://github.com/ErnyTech/p7zip/commit/26d66da98c4002dbc949d25b7ba41ba51d02942e
Sorry for making you commit a sin of the church of Emacs

**Comment by RogueScholar** [comment]
Haha, all is forgiven! I got quite a kick out of it, talking to myself the whole time about whose grave I could've stepped on that they would think of such a diabolical plan as to curse my archive manager to only let me view files in vim. Thanks for addressing it so quickly. :pray:
