### ISSUE TITLE
Read/write files on removable storage devices turns itself off.

### ISSUE THREAD

**Issue by Natetronn** [ErnyTech/p7zip#9]
Possible bug with permissions. Read/write files on removable storage devices turns itself off.

It seems to actually work, at least it did once, when turning this permission on (I tested it working; it found an external HDD that wasn't coming up before in the file manager) but, when you go back into the permission again it appears to have turned itself off. 

To duplicated issue: 

Go to the Ubuntu Software > P7Zip - Desktop > Permissions. Then turn on "Read/write files on removable storage devices", a window pops up asking for your password; enter password, close the window, open permissions again and the "Read/write files on removable storage devices" is off again.

Ubuntu 18.04.3 LTS
Gnome 3.28.2

**Comment by ErnyTech** [comment]
This issue is not related to p7zip-desktop, which does nothing more than use the classic snap permissions

Please forward the report to snapd and/or Ubuntu Store

I can do nothing to mitigate this problem, I thank you anyway for reporting
